#include <cstdio>
#include <cstdlib>
#include <iostream>

#include "aether/RandomVar.h"

int
main(int argc, char **argv)
{
  // Create a symbolic uniform random variable
  aether::variable<0> u;

  // Transform u -> sin(u)
  auto rv = make_random_var(sin(u));

  // Draw a sample from rv
  auto x = rv.Sample(0.75);

  // Compute the PDF of x using Aether's provided Pdf method
  auto pdfX = x.Pdf();

  // Compute the PDF of some other value not generated by rv
  auto pdfOther = x.Pdf(0.2);

  // x is a symbolic; x.Value() obtains the actual stored sample value
  std::cout << "x: " << x.Value() << std::endl;
  std::cout << "pdfX: " << pdfX << std::endl;
  std::cout << "pdfOther: " << pdfOther << std::endl;

  return EXIT_SUCCESS;
}
